In [ ]:
import pandas as pd
import numpy as np
print("Setup successful!")

Setup successful!

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/student-mat.csv')
print("Dataset loaded successfully!")
print("Dataset shape:",df.shape)
df.head()

Dataset loaded successfully!
Dataset shape: (395, 1)

  school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/student-mat.csv')
print("Dataset shape:",df.shape)
print("\nFirst 5 rows of the dataset:")
display(df.head())
print("\nMissing values in each column:")
print(df.isnull().sum())
print("\nDataset information:")
df.info()

Dataset shape: (395, 1)

First 5 rows of the dataset:

  school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...

Missing values in each column:
school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3    0
dtype: int64

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                               --------------  -----
 0   school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3  395 non-null    object
dtypes: object(1)
memory usage: 3.2+ KB

In [ ]:
import pandas as pd
import numpy as np
import os
print("Files:", os.listdir('/content'))

Files: ['.config', 'student-mat.csv', 'sample_data']

In [ ]:
df=pd.read_csv('/content/student-mat.csv', sep=';')
print("Dataset loaded successfully!")
print("Rows and columns:",df.shape)
display(df.head())
print("\nMissing values:")
print(df.isnull().sum())
print("\nDataset information:")
df.info

Dataset loaded successfully!
Rows and columns: (395, 33)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

Missing values:
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

Dataset information:

<bound method DataFrame.info of     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]>

In [ ]:
missing_values=df.isnull().sum()
print("Missing values before cleaning:")
print(missing_values[missing_values>0])
print("\nTotal missing values:",df.isnull().sum().sum())

Missing values before cleaning:
Series([], dtype: int64)

Total missing values: 0

In [ ]:
numerical_cols=df.select_dtypes(include=np.number).columns
categorical_cols=df.select_dtypes(exclude=np.number).columns
for col in numerical_cols:
       df[col]=df[col].fillna(df[col].median())
for col in categorical_cols:
       if df[col].isnull() .any():
        df[col]=df[col].fillna(df[col].mode()[0])
print("Missing values after cleaning:",df.isnull().sum().sum())
print("Dataset shape:",df.shape)

Missing values after cleaning: 0
Dataset shape: (395, 33)

In [ ]:
numerical_cols=df.select_dtypes(include=np.number).columns
for col in numerical_cols:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  outliers = df[(df[col] < lower_bound) | (df[col]>upper_bound)]
  if len(outliers)>0:
    print(f"{col}:{len(outliers)} outliers")

age:1 outliers
Fedu:2 outliers
traveltime:8 outliers
studytime:27 outliers
failures:83 outliers
famrel:26 outliers
freetime:19 outliers
Dalc:18 outliers
absences:15 outliers
G2:13 outliers

In [ ]:
for col in numerical_cols:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  df[col]=df[col].clip(lower=lower_bound,upper=upper_bound)
  print("Outliers capping completed.")
  print("Dataset shape:",df.shape)

Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)
Outliers capping completed.
Dataset shape: (395, 33)

In [ ]:
df['total_grade']= df['G1']+df['G2']+df['G3']
df['average_grade']= df[['G1','G2','G3']].mean(axis=1)
df['passed']= np.where(df['G3']>=10,'Yes','No')
df['study_category']= np.where(df['studytime']>=3,'High study time','Low study time')
print("New features created successfully!")
display(df[['G1', 'G2', 'G3', 'total_grade', 'average_grade','passed', 'study_category']].head())
print("\nUpdated dataset shape:",df.shape)

New features created successfully!

   G1  G2  G3  total_grade  average_grade passed   study_category
0   5   6   6           17       5.666667     No   Low study time
1   5   5   6           16       5.333333     No   Low study time
2   7   8  10           25       8.333333    Yes   Low study time
3  15  14  15           44      14.666667    Yes  High study time
4   6  10  10           26       8.666667    Yes   Low study time

Updated dataset shape: (395, 37)

In [ ]:
print("Dataset shape:", df.shape)
print("\nMissing values remaining:",df.isnull().sum().sum())
print("\nFirst 5 rows of the updated dataset:")
display(df.head())

Dataset shape: (395, 37)

Missing values remaining: 0

First 5 rows of the updated dataset:

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,Walc,health,absences,G1,G2,G3,total_grade,average_grade,passed,study_category
0,GP,F,18,U,GT3,A,4,4.0,at_home,teacher,...,1,3,6,5,6,6,17,5.666667,No,Low study time
1,GP,F,17,U,GT3,T,1,1.0,at_home,other,...,1,3,4,5,5,6,16,5.333333,No,Low study time
2,GP,F,15,U,LE3,T,1,1.0,at_home,other,...,3,3,10,7,8,10,25,8.333333,Yes,Low study time
3,GP,F,15,U,GT3,T,4,2.0,health,services,...,1,5,2,15,14,15,44,14.666667,Yes,High study time
4,GP,F,16,U,GT3,T,3,3.0,other,other,...,2,5,4,6,10,10,26,8.666667,Yes,Low study time

In [ ]:
df.to_csv('/content/cleaned-student_data.csv', index=False)
print("Dataset saved successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset saved successfully!
Rows: 395
Columns: 37